### Tensorflow Tutorial

#### Indexing

In [2]:
import tensorflow as tf
import numpy as np

2023-08-10 15:45:18.453581: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


VOC-NOTICE: GPU memory for this assignment is capped at 1024MiB


2023-08-10 15:45:21.429326: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


In [4]:
x = tf.random.normal([3, 3, 2])
x

<tf.Tensor: shape=(3, 3, 2), dtype=float32, numpy=
array([[[-0.9639039 , -1.2523714 ],
        [ 0.17772864, -0.31599933],
        [ 0.78930676,  1.302113  ]],

       [[-0.7442872 ,  0.4818864 ],
        [ 0.7939833 ,  0.36001036],
        [ 0.47740707,  0.37153813]],

       [[-0.16507536, -1.4024585 ],
        [ 0.7576146 , -0.48176548],
        [-1.5951948 , -0.18479188]]], dtype=float32)>

In [5]:
#first matrix
x[0]

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.9639039 , -1.2523714 ],
       [ 0.17772864, -0.31599933],
       [ 0.78930676,  1.302113  ]], dtype=float32)>

In [6]:
#second matrix, third row
x[1][2]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.47740707, 0.37153813], dtype=float32)>

In [8]:
#third matrix, first row, last element
x[2][0][1]

<tf.Tensor: shape=(), dtype=float32, numpy=-1.4024585>

#### Slicing

In [9]:
x

<tf.Tensor: shape=(3, 3, 2), dtype=float32, numpy=
array([[[-0.9639039 , -1.2523714 ],
        [ 0.17772864, -0.31599933],
        [ 0.78930676,  1.302113  ]],

       [[-0.7442872 ,  0.4818864 ],
        [ 0.7939833 ,  0.36001036],
        [ 0.47740707,  0.37153813]],

       [[-0.16507536, -1.4024585 ],
        [ 0.7576146 , -0.48176548],
        [-1.5951948 , -0.18479188]]], dtype=float32)>

In [14]:
#second matrix, second row onwards
x[1][1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.7939833 , 0.36001036],
       [0.47740707, 0.37153813]], dtype=float32)>

In [16]:
##third matrix, first two rows
x[2][:2]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.16507536, -1.4024585 ],
       [ 0.7576146 , -0.48176548]], dtype=float32)>

#### Reshaping

In [19]:
x = tf.range(96)
x

<tf.Tensor: shape=(96,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95], dtype=int32)>

In [20]:
x1 = tf.reshape(x, [2,48])
x1

<tf.Tensor: shape=(2, 48), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]],
      dtype=int32)>

In [21]:
x2 = tf.reshape(x, [2, 4, 12])
x2

<tf.Tensor: shape=(2, 4, 12), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]]], dtype=int32)>

In [22]:
x3 = tf.reshape(x, [2, 4, 4, 3])
x3

<tf.Tensor: shape=(2, 4, 4, 3), dtype=int32, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89],
         [90, 91, 92],
         [93, 94, 95]]]], dtype=int32)>

In [23]:
x = tf.range(24)
x

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int32)>

In [24]:
x1 = tf.reshape(x, [2, -1])
x1

<tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]], dtype=int32)>

In [28]:
x2 = tf.reshape(x, [2, 12])
x2

<tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]], dtype=int32)>

In [29]:
x3 = tf.reshape(x1, [2, 3, -1])
x3

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)>

### Mathematical operations

In [30]:
x = tf.range(10)
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [31]:
y = tf.constant(4)
y

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [32]:
x + y

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13], dtype=int32)>

In [33]:
x - y

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5], dtype=int32)>

In [34]:
x/y

<tf.Tensor: shape=(10,), dtype=float64, numpy=array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25])>

In [35]:
tf.pow(x, 2)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [43]:
#type casting
x = tf.cast(x, dtype = tf.float32)
#square root
tf.pow(x, 0.5)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.236068 ,
       2.4494898, 2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [47]:
#Exponential
tf.exp(4.)

<tf.Tensor: shape=(), dtype=float32, numpy=54.59815>

In [48]:
#Logarithmic
tf.math.log(x)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([     -inf, 0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 ,
       1.7917595, 1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [51]:
#matrix multiplication

a = tf.random.normal([3,2])
b = tf.random.normal([2,3])

a@b

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.6830379 ,  0.6257789 ,  1.306679  ],
       [-2.001636  , -0.87165326, -1.7030064 ],
       [-0.8553676 ,  0.44712654,  0.2305419 ]], dtype=float32)>